#!/usr/bin/bash
. inv/list

shutdown_vm(){
  for vm in ${allvms[@]}
  do
    state=$(sudo virsh domstate $vm)

    if [ "$state" != "shut off" ]; then
      sudo virsh shutdown $vm
    fi
  done
}

shutdown_vm
